# Configuration for Google Cloud Platform (GCP) deployment
# See here for documentation: https://cloud.google.com/appengine/docs/standard/php/config/appref
runtime: php55

handlers:
- url: /
  script: index.html
- url: /(.+\.php)$
  script: \1 
- url: /(.+\.css)$
  static_files: \1
  upload: .+\.css$
  application_readable: true
- url: /(.+\.js)$
  static_files: \1
  upload: .+\.js$
  application_readable: true
- url: /(.+\.ico)$
  static_files: \1
  upload: .+\.ico$
  application_readable: true